---
version: '2'

networks:
  backend:
    driver: bridge

services:
  koha_patched:
    container_name: koha_patched
    build:
      context: "${KOHAPATH}/koha-patched"
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - sip_patched
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
      - MKNOD
    volumes:
      - ${KOHAPATH}/koha-patched/patches:/patches
      - ${KOHAPATH}/koha-patched/debian:/debian
    environment:
      KOHA_VERSION: "${KOHA_VERSION}"
      KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
      KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
      KOHA_INSTANCE: "$KOHA_INSTANCE"
      KOHA_DBHOST: koha_mysql
      DEFAULT_LANGUAGE: nb-NO
      EMAIL_ENABLED: "True"
      SMTP_SERVER_HOST: mailrelay # access through network 'backend'
      SMTP_SERVER_PORT: 2525
      MESSAGE_QUEUE_FREQUENCY: 1
      SMS_SERVER_HOST: "${SMS_SERVER_HOST}"
      API_PASSPHRASE: "${API_PASSPHRASE}"
      NLBASEUSER: "${NLBASEUSER}"
      NLBASEPASS: "${NLBASEPASS}"
      NLVENDORURL: "${NLVENDORURL}"
      NLVENDORUSER: "${NLVENDORUSER}"
      NLVENDORPASS: "${NLVENDORPASS}"
      NLVENDORKEY: "${NLVENDORKEY}"
    ports:
      - "6001:6001"
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  sip_patched:
    container_name: sip_proxy_patched
    image: "digibib/tcp-proxy:14dc5417bf211317351a0bae084db12c64a1dd45"
    networks:
      - backend
    ports:
      - "6003:9999"
    command:
      - "/app/tcp-proxy"
      - "-vv"
      - "-r"
      - "${HOST}:${SIP_PORT}"
      - "-replace=(|AB)10([0-9]{14})~$$1$$2"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
